### ISSUE TITLE
Game crashes upon start

### ISSUE THREAD

**Issue by Hypsandar** [Leo40Git/ChainCraft#3]
Error: java.lang.NoSuchMethodError: com.moddy10.chaincraft.items.ItemChainmailPlate.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/item/Item;

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.5.1.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 7/29/17 7:19 PM
Description: Initializing game

java.lang.NoSuchMethodError: com.moddy10.chaincraft.items.ItemChainmailPlate.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/item/Item;
	at com.moddy10.chaincraft.items.ItemChainmailPlate.<init>(ItemChainmailPlate.java:17)
	at com.moddy10.chaincraft.proxy.CommonProxy.registerItems(CommonProxy.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_CommonProxy_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:726)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.moddy10.chaincraft.items.ItemChainmailPlate.<init>(ItemChainmailPlate.java:17)
	at com.moddy10.chaincraft.proxy.CommonProxy.registerItems(CommonProxy.java:48)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_11_CommonProxy_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:726)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:605)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 123749624 bytes (118 MB) / 445841408 bytes (425 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2426 Optifine OptiFine_1.12_HD_U_C4 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2426.jar) 
	UCH	forge{14.21.1.2426} [Minecraft Forge] (forge-1.12-14.21.1.2426.jar) 
	UCH	rpghud{3.6.3} [RPG-Hud] ([1.12] RPG-HUD-3.6.3.jar) 
	UCH	ambience{GRADLE:VERSION-GRADLE:BUILD} [Ambience] (Ambience 1.1-9.jar) 
	UCH	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCH	customcrosshairmod{0.8.1} [Custom Crosshair Mod] (crosshairmod-v0.8.1-forge-mc1.12.jar) 
	UCH	customnpcs{1.12} [CustomNPCs] (CustomNPCs_1.12.0(22jul17)beta.jar) 
	UCH	dirt2path{1.7.0} [Dirt2Path] (dirt2path-1.7.0.jar) 
	UCH	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCH	fw{1.6.0} [Fullscreen Windowed] (FullscreenWindowed-1.12-1.6.0.jar) 
	UCH	chaincraft{1.0.1} [JACCM] (jaccm-1.1.0.jar) 
	UCH	jei{4.7.2.77} [Just Enough Items] (jei_1.12-4.7.2.77.jar) 
	UCH	jepb{1.2.1} [Just Enough Pattern Banners] (jepb-1.12-1.2.1.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	mobends{0.24} [Mo' Bends] (mobends-0.24_for_MC-1.12.jar) 
	UCH	nex{2.1.10.11} [NetherEx] (NetherEx-1.12-2.1.10.11.jar) 
	UCH	overlord{2.4.3} [Overlord] (Overlord-1.12-2.4.3.jar) 
	UCH	harvestcraft{1.12b} [Pam's HarvestCraft] (Pam's HarvestCraft 1.12b.jar) 
	UCH	prefab{1.3.0.1} [Prefab] (prefab-1.3.0.1.jar) 
	UCH	r2s_c{1.2.0} [r2s_core] (r2s-Core-1.12-1.2.0.RELEASE.jar) 
	UCH	r2s_r{1.3.5} [r2s_Radio] (r2s-Radio-1.12-1.3.5.RELEASE.jar) 
	UCH	rustic{0.4} [Rustic] (rustic-0.4.jar) 
	UCH	vimmersion{2.0.2.0} [Vanilla Immersion] (vanilla-immersion-1.12-2.0.2.0.jar) 
	UCH	waystones{4.0.5} [Waystones] (Waystones_1.12-4.0.5..jar) 
	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.5.1.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 369.09' Renderer: 'GeForce 920M/PCIe/SSE2'
	Launched Version: 1.12-forge1.12-14.21.1.2426
	LWJGL: 2.9.4
	OpenGL: GeForce 920M/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Hypsandar's Faithful Paintins 1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 369.09
	OpenGlRenderer: GeForce 920M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Leo40Git** [comment]
Should be fixed in 1.1.1.
Get it [here](https://github.com/Leo40Git/ChainCraft/releases/tag/v1.1.1), update will be up on Curse soon.

**Comment by Hypsandar** [comment]
Thanks, that was quick. What triggered the crash?

**Comment by Leo40Git** [comment]
Apparently setting the unlocalized name via the setter doesn't work outside of a development environment.
1.1.1 fixes this by instead overriding the getter.

**Comment by Hypsandar** [comment]
Setter, getter? Do you mean marker, receiver?  What programming language are you working with?

**Comment by Leo40Git** [comment]
I'm working with Java.
